### ISSUE TITLE
While trying a payment: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>

### ISSUE THREAD

**Issue by ak1987** [xamelon/flutter_pay#14]
I tried to clone your project and proceed to test payment.
After checking if i am able to pay && payments with verified card (both are true) i tried to pay, but got error:

_Error: error.
Description: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>_

Nothing was changed in your code, not even a char.

**Log:**
```
Running "flutter pub get" in example...
Launching lib/main.dart on STF L09 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:37319/UDma2qSBCVs=/ws
Syncing files to device STF L09...
I/ViewRootImpl(15280): jank_removeInvalidNode jank list is null
D/AwareBitmapCacher(15280): handleInit switch not opened pid=15280
I/ter_pay_exampl(15280): Starting profile saver IsSaveProfileNow end.
V/AudioManager(15280): playSoundEffect   effectType: 0
V/AudioManager(15280): querySoundEffectsEnabled...
I/System.out(15280): getBaseCardPaymentMethod, authMethods: ["PAN_ONLY","CRYPTOGRAM_3DS"]
V/AudioManager(15280): playSoundEffect   effectType: 0
V/AudioManager(15280): querySoundEffectsEnabled...
I/System.out(15280): getBaseCardPaymentMethod, authMethods: ["PAN_ONLY","CRYPTOGRAM_3DS"]
V/AudioManager(15280): playSoundEffect   effectType: 0
V/AudioManager(15280): querySoundEffectsEnabled...
I/System.out(15280): Is test Environment: true
E/MethodChannel#flutter_pay(15280): Failed to handle method call
E/MethodChannel#flutter_pay(15280): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>
E/MethodChannel#flutter_pay(15280): 	at com.xamelon.flutter_pay.FlutterPayPlugin.requestPayment(FlutterPayPlugin.kt:164)
E/MethodChannel#flutter_pay(15280): 	at com.xamelon.flutter_pay.FlutterPayPlugin.onMethodCall(FlutterPayPlugin.kt:70)
E/MethodChannel#flutter_pay(15280): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_pay(15280): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_pay(15280): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_pay(15280): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_pay(15280): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#flutter_pay(15280): 	at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#flutter_pay(15280): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#flutter_pay(15280): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_pay(15280): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#flutter_pay(15280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/flutter (15280): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 
E/flutter (15280): 
E/flutter (15280):     Error: error.
E/flutter (15280):     Description: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>
E/flutter (15280): #0      FlutterPay.requestPayment (package:flutter_pay/src/flutter_pay.dart:102:7)
E/flutter (15280): <asynchronous suspension>
E/flutter (15280): 
```
**Flutter Doctor:**
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.104, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by kirya355** [comment]
Same issue

**Comment by feemagdev** [comment]
same issue. please resolve this issue

**Comment by realkalash** [comment]
Same

**Comment by yande-eghosa** [comment]
Same here

**Comment by Sambucho** [comment]
Google Pay needs "allowedAuthMethods" parameter for payment. This plugin doesn't provide it.
You can add this code
  "allowedAuthMethods": [],
to flutter_pay.dart in your cache on 68 line
