### ISSUE TITLE
Android check pay

### ISSUE THREAD

**Issue by tashone** [xamelon/flutter_pay#15]
Hello.
When I run 
> flutterPay.canMakePayments()

I get error:

> I/System.out(20086): getBaseCardPaymentMethod, authMethods: ["PAN_ONLY","CRYPTOGRAM_3DS"]
W/System.err(20086): com.google.android.gms.common.api.ApiException: 10: 
W/System.err(20086): 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.1.0:6)
W/System.err(20086): 	at com.google.android.gms.internal.wallet.zzw.zza(com.google.android.gms:play-services-wallet@@18.0.0:8)
W/System.err(20086): 	at com.google.android.gms.internal.wallet.zzt.dispatchTransaction(com.google.android.gms:play-services-wallet@@18.0.0:40)
W/System.err(20086): 	at com.google.android.gms.internal.wallet.zza.onTransact(com.google.android.gms:play-services-wallet@@18.0.0:13)
W/System.err(20086): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
W/System.err(20086): 	at android.os.Binder.execTransact(Binder.java:994)

Can You help with this error. Earlier I tried with other packet and it was ok, but now I has error with both packets...

**Comment by tashone** [comment]
I found that this error have no if the dart 2.12 version. But right now I can't migrate all project in nullSafety. Have ideas?

**Comment by tashone** [comment]
I think you need update some versions of android services\includes.
Included other packet 
mad_pay: ^2.1.0
and i haven't this error....

**Comment by tashone** [comment]
I found what need to add into your packet. Need change manifest
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.xamelon.flutter_pay">
    <application>
        <meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />
    </application>
</manifest>
on this.

and maybe update version of lib
implementation 'com.google.android.gms:play-services-wallet:18.1.2'
