### ISSUE TITLE
For Android the package is giving error

### ISSUE THREAD

**Issue by jk-hub** [xamelon/flutter_pay#16]
when we run and check flutterPay.canMakePayments() this method is giving false in return despite we have google pay on physical device 
Error on debug: 
I/System.out(12880): Is test Environment: true
I/System.out(12880): getBaseCardPaymentMethod, authMethods: ["PAN_ONLY","CRYPTOGRAM_3DS"]
W/System.err(12880): com.google.android.gms.common.api.ApiException: 10:
W/System.err(12880): 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.5.0:6)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zzab.zza(com.google.android.gms:play-services-wallet@@18.1.2:8)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zzy.dispatchTransaction(com.google.android.gms:play-services-wallet@@18.1.2:40)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zza.onTransact(com.google.android.gms:play-services-wallet@@18.1.2:13)
W/System.err(12880): 	at android.os.Binder.execTransact(Binder.java:731)
I/System.out(12880): getBaseCardPaymentMethod, authMethods: ["PAN_ONLY","CRYPTOGRAM_3DS"]
W/System.err(12880): com.google.android.gms.common.api.ApiException: 10:
W/System.err(12880): 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.5.0:6)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zzab.zza(com.google.android.gms:play-services-wallet@@18.1.2:8)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zzy.dispatchTransaction(com.google.android.gms:play-services-wallet@@18.1.2:40)
W/System.err(12880): 	at com.google.android.gms.internal.wallet.zza.onTransact(com.google.android.gms:play-services-wallet@@18.1.2:13)
W/System.err(12880): 	at android.os.Binder.execTransact(Binder.java:731)
I/flutter (12880): payment kar ne de ga kya false
I/flutter (12880): card se payment kar ne de ga kya false
E/MethodChannel#flutter_pay(12880): Failed to handle method call
E/MethodChannel#flutter_pay(12880): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>
E/MethodChannel#flutter_pay(12880): 	at com.xamelon.flutter_pay.FlutterPayPlugin.requestPayment(FlutterPayPlugin.kt:164)
E/MethodChannel#flutter_pay(12880): 	at com.xamelon.flutter_pay.FlutterPayPlugin.onMethodCall(FlutterPayPlugin.kt:70)
E/MethodChannel#flutter_pay(12880): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_pay(12880): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_pay(12880): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_pay(12880): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_pay(12880): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_pay(12880): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_pay(12880): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
E/MethodChannel#flutter_pay(12880): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_pay(12880): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_pay(12880): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (12880): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception:
E/flutter (12880):
E/flutter (12880):     Error: error.
E/flutter (12880):     Description: null cannot be cast to non-null type kotlin.collections.List<kotlin.String>
E/flutter (12880): #0      FlutterPay.requestPayment
E/flutter (12880): <asynchronous suspension>
E/flutter (12880): #1      AllTemplatesPageController.makePayment
E/flutter (12880): <asynchronous suspension>
E/flutter (12880):

Flutter doctor details : 
flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.985], locale en-IN)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (3 months ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\jk\AppData\Local\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\jk\AppData\Local\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • ASUS X00TD (mobile) • 192.168.0.101:5555 • android-arm64  • Android 9 (API 28)
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!

**Comment by Tumist76** [comment]
Fixed now

**Comment by jk-hub** [comment]
Great thanks
