### ISSUE TITLE
Crash after completing payment

### ISSUE THREAD

**Issue by Tumist76** [xamelon/flutter_pay#3]
Copypasted code from example app, from `makePayment()` method. Google Pay sheet sucessfully shows, but after payment confirming the app force closes.

Debug console output:
```
D/AndroidRuntime( 8517): Shutting down VM
E/AndroidRuntime( 8517): FATAL EXCEPTION: main
E/AndroidRuntime( 8517): Process: ru.mygeizer.mygeizer, PID: 8517
E/AndroidRuntime( 8517): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=991, result=-1, data=Intent { (has extras) }} to activity {ru.mygeizer.mygeizer/ru.mygeizer.mygeizer.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime( 8517): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 8517): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8517): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 8517): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 8517): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8517): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8517): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8517): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 8517): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 8517): 	at snail.app.flutter.google.pay.FlutterGooglePayPlugin.callToDartOnPaymentSuccess(FlutterGooglePayPlugin.java:126)
E/AndroidRuntime( 8517): 	at snail.app.flutter.google.pay.FlutterGooglePayPlugin.onActivityResult(FlutterGooglePayPlugin.java:291)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime( 8517): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime( 8517): 	... 11 more
I/Process ( 8517): Sending signal. PID: 8517 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Code snippet:
```
    FlutterPay flutterPay = FlutterPay();

    PaymentItem item = PaymentItem(name: "Оплата услуг автомойки", price: _sum);
    flutterPay.setEnvironment(environment: PaymentEnvironment.Test);
    List<PaymentItem> items = [
      PaymentItem(name: "Услуги автомойки GEIZER", price: _sum)
    ];

    flutterPay.setEnvironment(environment: PaymentEnvironment.Test);

    var token = await flutterPay.requestPayment(
      googleParameters: GoogleParameters(
        gatewayName: "example",
        gatewayMerchantId: "example_id",
      ),
      appleParameters:
          AppleParameters(merchantIdentifier: "merchant.flutterpay.example"),
      currencyCode: "RUB",
      countryCode: "RU",
      paymentItems: items,
    );
```

**Comment by Tumist76** [comment]
Nevermind, the problem was with another plugin that used the same channel names and was called too.
